apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - route.yaml

replicas:
  - name: operator-sync-server
    count: 2
  - name: operator-sync-worker
    count: 3