package consts

const (
	CONFIG_DEFAULT_IPFS_ENDPOINT = "https://ipfs-relay.crossbell.io/upload"

	CONFIG_DEFAULT_CONCURRENCY_CONTROL_STATEFUL  = 10 // Concurrency Control
	CONFIG_DEFAULT_CONCURRENCY_CONTROL_STATELESS = 50
	CONFIG_DEFAULT_CONCURRENCY_CONTROL_DIRECT    = 100

	CONFIG_DEFAULT_CROSSBELL_CHAIN_ID         = 3737 // Crossbell chain related
	CONFIG_DEFAULT_CROSSBELL_JSON_RPC         = "https://rpc.crossbell.io"
	CONFIG_DEFAULT_CROSSBELL_CONTRACT_ADDRESS = "0xa6f969045641Cf486a747A2688F3a5A6d43cd0D8"
)
