apiVersion: v1
kind: Secret
metadata:
  name: operator-sync-server
  namespace: crossbell
type: Opaque
stringData:
  DATABASE_CONNECTION_STRING: "<DATABASE_CONNECTION_STRING_DEV>"
  REDIS_CONNECTION_STRING: "<REDIS_CONNECTION_STRING_DEV>"
  MQ_CONNECTION_STRING: "<MQ_CONNECTION_STRING_DEV>"
  WORKER_RPC_PORT: "22915"
  WORKER_RPC_ENDPOINT: "opsync-worker.crossbell"
  MODE: "dev"