apiVersion: v1
kind: Service
metadata:
  name: opsync
  namespace: crossbell
spec:
  type: ClusterIP
  selector:
    app: operator-sync
    tier: server
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080