apiVersion: v1
kind: Secret
metadata:
  name: operator-sync-worker
  namespace: crossbell
type: Opaque
stringData:
  RSSHUB_STATEFUL: "<RSSHUB_ENDPOINT>"
  RSSHUB_STATELESS: "<RSSHUB_ENDPOINT>"
  IPFS_ENDPOINT: "<IPFS_ENDPOINT>"
  REDIS_CONNECTION_STRING: "<REDIS_CONNECTION_STRING_DEV>"
  MQ_CONNECTION_STRING: "<MQ_CONNECTION_STRING_DEV>"
  CONCURRENCY_CONTROL_STATEFUL: "10"
  CONCURRENCY_CONTROL_STATELESS: "50"
  CONCURRENCY_CONTROL_DIRECT: "100"
  CROSSBELL_CHAIN_ID: "3737"
  CROSSBELL_JSON_RPC: "https://rpc.crossbell.io"
  CROSSBELL_INDEXER: "https://indexer.crossbell.io"
  CROSSBELL_CONTRACT_ADDRESS: "0xa6f969045641Cf486a747A2688F3a5A6d43cd0D8"
  ETHEREUM_PRIVATE_KEY: "<ETHEREUM_PRIVATE_KEY>"
  ONCHAIN_WORKER: "true"
  WORKER_RPC_PORT: "22915"
  MODE: "dev"