apiVersion: v1
kind: Service
metadata:
  name: opsync-worker
  namespace: crossbell
spec:
  type: ClusterIP
  selector:
    app: operator-sync
    tier: worker
  ports:
    - name: rpc
      protocol: TCP
      port: 22915
      targetPort: 22915