name: Build and Deploy
on:
  push:
    branches:
      - develop
      - main
    tags:
      - v*
jobs:
  build:
    uses: NaturalSelectionLabs/Daedalus/.github/workflows/docker-tpl.yaml@main
    with:
      images: flosspicks/opsync
      context: .
      dockerfile: ./deploy/dockerfile/Dockerfile
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  deploy-dev:
    if: github.ref == 'refs/heads/develop'
    uses: NaturalSelectionLabs/Daedalus/.github/workflows/deploy-v3-tpl.yaml@main
    needs:
      - build
    with:
      images: flosspicks/opsync
      tag: sha-${{ github.sha }}
      cluster: dev
      namespace: crossbell
      releaseName: operator-sync
      revision: develop
      dir: deploy/dev
    secrets:
      ARGOCD_TOKEN: ${{ secrets.ARGOCD_TOKEN }}
  deploy-prod:
    if: github.ref == 'refs/heads/main'
    uses: NaturalSelectionLabs/Daedalus/.github/workflows/deploy-v3-tpl.yaml@main
    needs:
      - build
    with:
      images: flosspicks/opsync
      tag: sha-${{ github.sha }}
      cluster: prod
      namespace: crossbell
      releaseName: operator-sync
      revision: main
      dir: deploy/prod
    secrets:
      ARGOCD_TOKEN: ${{ secrets.ARGOCD_TOKEN }}
